server:
  port: 8081

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
