server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
